apiVersion: v1
kind: Namespace
metadata:
  name: recommendation-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  namespace: recommendation-service
  labels:
    app: recommendation-service
spec:
  selector:
    matchLabels:
      app: recommendation-service
  replicas: 2
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
        - name: recommendation-service
          image: ghcr.io/spotify-portal-public-demo/recommendation-service:latest # {"$imagepolicy": "flux-system:recommendation-service"}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: recommendation-service
  labels:
    app: recommendation-service
spec:
  clusterIP: None
  selector:
    app: recommendation-service
  ports:
    - name: grpc
      port: 9090
